// <auto-generated />
using System;
using Entity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Entity.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entity.Model.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("inventory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf744495-5c40-4c95-90fe-aa18ff8c1414"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5946),
                            IsActive = true,
                            ProductId = new Guid("664f59e6-f1f2-4165-a9d6-75aab245f8cf"),
                            Stock = 30,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5946)
                        },
                        new
                        {
                            Id = new Guid("c3763260-4eeb-4bf8-b7f5-1c6337e23b3b"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5950),
                            IsActive = true,
                            ProductId = new Guid("bbadc45e-5f6d-452e-81ec-228f02c5960d"),
                            Stock = 20,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5950)
                        },
                        new
                        {
                            Id = new Guid("6a5a89ab-1f5d-447e-931c-50090a327eca"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5955),
                            IsActive = true,
                            ProductId = new Guid("9207c8c3-fe61-4111-847c-60b1d739890d"),
                            Stock = 15,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5955)
                        },
                        new
                        {
                            Id = new Guid("905eac19-6e74-4054-92f3-74ab05c3e056"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5956),
                            IsActive = true,
                            ProductId = new Guid("c79f9283-8aa0-4acc-b9a0-09444e38e6cd"),
                            Stock = 50,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5956)
                        },
                        new
                        {
                            Id = new Guid("8cbc3905-35fd-4497-9c87-5ec4bf37e545"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5958),
                            IsActive = true,
                            ProductId = new Guid("8112b552-db97-4f24-866b-58f7e2dbdc20"),
                            Stock = 40,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5958)
                        },
                        new
                        {
                            Id = new Guid("2e76c0d3-8095-49ea-b1da-6b5e0c580e65"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5959),
                            IsActive = true,
                            ProductId = new Guid("c68b15ac-86ee-4d93-a9cd-9c8e5886df29"),
                            Stock = 25,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5960)
                        },
                        new
                        {
                            Id = new Guid("e6d185e7-3290-455b-b3ed-efa3a47dd50b"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5961),
                            IsActive = true,
                            ProductId = new Guid("d2cf2963-7344-4230-a040-455ee02c6dc7"),
                            Stock = 60,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5961)
                        },
                        new
                        {
                            Id = new Guid("887d5852-362c-4d20-9acf-e55fbe28c7ba"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5962),
                            IsActive = true,
                            ProductId = new Guid("97ba7ea2-d733-425a-8684-115057976980"),
                            Stock = 35,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5962)
                        },
                        new
                        {
                            Id = new Guid("28a9ecb0-39a2-4447-ac50-43754146234c"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5964),
                            IsActive = true,
                            ProductId = new Guid("a1464c2c-a4a1-4a7e-8260-3fc23c8cd3e8"),
                            Stock = 45,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5964)
                        },
                        new
                        {
                            Id = new Guid("d9850a9f-771f-4955-8f74-5164362545d8"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5965),
                            IsActive = true,
                            ProductId = new Guid("713ecd46-6bb2-401b-b4ed-f8018d9ea7ea"),
                            Stock = 30,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5965)
                        },
                        new
                        {
                            Id = new Guid("bea43e36-9da0-4372-92de-38871e6920e8"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5969),
                            IsActive = true,
                            ProductId = new Guid("3ef4fdba-4592-40b7-9ce8-f9fa927060c0"),
                            Stock = 20,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5969)
                        },
                        new
                        {
                            Id = new Guid("71769a72-7f4e-40fa-8e59-1a484ac5dd0e"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5970),
                            IsActive = true,
                            ProductId = new Guid("43e4e9d8-3251-49c5-9221-c1f22f030ec6"),
                            Stock = 50,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5970)
                        },
                        new
                        {
                            Id = new Guid("ad2e3f70-89cc-47e0-88ba-2935752eba27"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5972),
                            IsActive = true,
                            ProductId = new Guid("4c84ab00-c4e0-4e3a-8ab5-ca1338acd88e"),
                            Stock = 15,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5972)
                        },
                        new
                        {
                            Id = new Guid("953e772a-0b9d-4dba-9383-b18ee9fefdec"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5973),
                            IsActive = true,
                            ProductId = new Guid("a78d2f3b-5b7d-415e-b006-e377efbe4392"),
                            Stock = 70,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5974)
                        },
                        new
                        {
                            Id = new Guid("ad21eedd-0b7c-4ef0-828e-d1162e949d8a"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5975),
                            IsActive = true,
                            ProductId = new Guid("92e4d9bf-ed54-494b-8294-967ea19bc2db"),
                            Stock = 25,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5975)
                        },
                        new
                        {
                            Id = new Guid("2cf5f6b4-f9cd-4825-b8dd-ed8f9b96dbae"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5976),
                            IsActive = true,
                            ProductId = new Guid("2e0894c6-1ba6-4b00-bef9-d95a21e30ef0"),
                            Stock = 40,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5976)
                        },
                        new
                        {
                            Id = new Guid("0bd3c9e4-bd7c-4d41-8809-3fc33977b5d1"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5978),
                            IsActive = true,
                            ProductId = new Guid("bef99a10-b032-4e81-9112-c91cb7971fb3"),
                            Stock = 60,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5978)
                        },
                        new
                        {
                            Id = new Guid("13620c8b-8f76-4859-828d-82a3a8fa357b"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5979),
                            IsActive = true,
                            ProductId = new Guid("6424bae2-7049-45a7-9529-6c0298b394dc"),
                            Stock = 10,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5980)
                        },
                        new
                        {
                            Id = new Guid("96af6e7d-61e4-4b67-ac0d-dd98d34ee752"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5983),
                            IsActive = true,
                            ProductId = new Guid("9c9c38ef-3455-4f57-9cb8-f9a33b58fe2a"),
                            Stock = 30,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5983)
                        },
                        new
                        {
                            Id = new Guid("8bf2f451-575d-4443-96e4-eb3fab2d9748"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5985),
                            IsActive = true,
                            ProductId = new Guid("652ab917-199b-4268-8b92-39bf71e859ce"),
                            Stock = 50,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5985)
                        },
                        new
                        {
                            Id = new Guid("410f97ac-22c7-4e59-a162-056e9d88feb5"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5986),
                            IsActive = true,
                            ProductId = new Guid("04765c15-3ad7-4ed0-a604-8cb4078887b4"),
                            Stock = 15,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5986)
                        },
                        new
                        {
                            Id = new Guid("1c88d82d-b248-4b4f-a9ed-8f4aab8f1040"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5987),
                            IsActive = true,
                            ProductId = new Guid("6dd257e5-f534-49dd-9c67-c3ab7608de70"),
                            Stock = 30,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5988)
                        },
                        new
                        {
                            Id = new Guid("b0fc1da8-dd59-4e28-b6a7-4f4276443473"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5989),
                            IsActive = true,
                            ProductId = new Guid("535d56a0-5feb-48f6-853e-4217c5c95fa2"),
                            Stock = 10,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5989)
                        },
                        new
                        {
                            Id = new Guid("6f34d254-c816-403c-9887-3370995155d7"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5990),
                            IsActive = true,
                            ProductId = new Guid("f6dc236e-7bd3-49cc-a611-c3386e7ab1b1"),
                            Stock = 25,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5990)
                        },
                        new
                        {
                            Id = new Guid("4b585114-e0e2-4b76-93e1-1526da09beee"),
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5992),
                            IsActive = true,
                            ProductId = new Guid("8e52187f-fd1f-4add-8f5b-a523885e4472"),
                            Stock = 40,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5992)
                        },
                        new
                        {
                            Id = new Guid("92fbd71a-39d8-43a8-bcf5-50bd3e6bcc57"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5993),
                            IsActive = true,
                            ProductId = new Guid("4db5800f-fd90-47b2-bf86-0abc27020e1e"),
                            Stock = 20,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5993)
                        },
                        new
                        {
                            Id = new Guid("818752a2-591b-4127-b895-3bd9f1abd901"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5997),
                            IsActive = true,
                            ProductId = new Guid("9e9a5a67-7ffa-49f1-b015-fa6de5f5b581"),
                            Stock = 30,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5997)
                        },
                        new
                        {
                            Id = new Guid("2a8a0007-d5bb-4a64-aa04-0584c110edb1"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5998),
                            IsActive = true,
                            ProductId = new Guid("2303a938-1f05-42bb-a5f0-99e7dbf77188"),
                            Stock = 15,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5998)
                        },
                        new
                        {
                            Id = new Guid("df1aa1ad-f825-4f21-b808-f23d9fc3abee"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6000),
                            IsActive = true,
                            ProductId = new Guid("9d7febe0-cb68-4d36-9a8f-4e845109e53c"),
                            Stock = 50,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6000)
                        },
                        new
                        {
                            Id = new Guid("947dae7e-3ef4-42f6-9e35-9502a1218d8e"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6001),
                            IsActive = true,
                            ProductId = new Guid("eab5c8b2-8ae2-4bf8-827c-789ed415792c"),
                            Stock = 20,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6001)
                        },
                        new
                        {
                            Id = new Guid("e865108c-44b9-47a8-b6a4-f3e723957cc0"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6002),
                            IsActive = true,
                            ProductId = new Guid("28804ab1-8b21-411d-8493-cafafbd32670"),
                            Stock = 40,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6003)
                        },
                        new
                        {
                            Id = new Guid("949f6213-de71-4bc9-a719-9d71f8987ef7"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6004),
                            IsActive = true,
                            ProductId = new Guid("231c7d5a-b2c9-4163-8405-147c8eec3ff6"),
                            Stock = 10,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6004)
                        },
                        new
                        {
                            Id = new Guid("856e6c85-3514-4efe-aa3b-683f957067ed"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6006),
                            IsActive = true,
                            ProductId = new Guid("8d22a54b-4ee5-4776-9f37-6ee36b72e046"),
                            Stock = 30,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6006)
                        },
                        new
                        {
                            Id = new Guid("a53c3a65-5f06-4e32-a597-669b6d7febf2"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6007),
                            IsActive = true,
                            ProductId = new Guid("1c9b64eb-992f-4523-9582-935af6ffc634"),
                            Stock = 25,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6007)
                        },
                        new
                        {
                            Id = new Guid("8366f230-0577-41ea-bd05-38d538137562"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6011),
                            IsActive = true,
                            ProductId = new Guid("dbd0b3c5-6821-48f0-ac39-b56bf14cca52"),
                            Stock = 40,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6011)
                        },
                        new
                        {
                            Id = new Guid("03bcc405-57e5-4a96-9e76-90714de18852"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6012),
                            IsActive = true,
                            ProductId = new Guid("8c96f86f-2e58-4d74-8ddb-d9c6539ae08a"),
                            Stock = 30,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6013)
                        },
                        new
                        {
                            Id = new Guid("67215c7d-3183-4d35-b216-193b47b4f423"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6014),
                            IsActive = true,
                            ProductId = new Guid("5121ab0e-8697-4e64-aa0e-ae5f70a64699"),
                            Stock = 15,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6014)
                        },
                        new
                        {
                            Id = new Guid("975640e7-47ac-4d2a-ba1a-1905fdb405e3"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6015),
                            IsActive = true,
                            ProductId = new Guid("efae2427-0391-4b22-af71-94189ea04421"),
                            Stock = 50,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6015)
                        },
                        new
                        {
                            Id = new Guid("e32e8967-19d4-48e9-a4dc-2e44e6e6e2a8"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6017),
                            IsActive = true,
                            ProductId = new Guid("022f1827-3348-42e5-8a5a-c00fcec98e6d"),
                            Stock = 60,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6017)
                        },
                        new
                        {
                            Id = new Guid("2be60688-2bb5-4450-bff7-06f28bb72976"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6018),
                            IsActive = true,
                            ProductId = new Guid("35492266-0b0b-40d2-a4bf-a1b001c9af71"),
                            Stock = 70,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6018)
                        },
                        new
                        {
                            Id = new Guid("8d9d9e0f-75ca-40cf-80e4-1a92a3f9f112"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6019),
                            IsActive = true,
                            ProductId = new Guid("3ff76b36-ae8f-4fc8-916a-b5cb0cbb365b"),
                            Stock = 20,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6020)
                        },
                        new
                        {
                            Id = new Guid("8fd452b5-2cc8-4a03-b44f-5519efb442fc"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6021),
                            IsActive = true,
                            ProductId = new Guid("ec594480-1cdf-4f6a-8f59-a57252e61b46"),
                            Stock = 30,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6021)
                        },
                        new
                        {
                            Id = new Guid("5a81ead7-10d2-4fb0-bda7-98dc8fd4dba2"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6024),
                            IsActive = true,
                            ProductId = new Guid("4a90ec34-7c7c-4b50-947f-5489894e423a"),
                            Stock = 10,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6025)
                        },
                        new
                        {
                            Id = new Guid("07b68e2c-5bc2-4bab-8f79-1c7e27d30b45"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6026),
                            IsActive = true,
                            ProductId = new Guid("083e888a-6a3b-485c-ba68-33e77c3e15ab"),
                            Stock = 25,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6026)
                        },
                        new
                        {
                            Id = new Guid("578bec18-77ef-4860-b3b2-9aa02db1c9d6"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6027),
                            IsActive = true,
                            ProductId = new Guid("de93253a-9c39-4242-b790-02c6c5a7ce7d"),
                            Stock = 40,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6028)
                        },
                        new
                        {
                            Id = new Guid("526637a7-155f-4972-8b7c-968504f1d432"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6029),
                            IsActive = true,
                            ProductId = new Guid("10a91197-d1ac-4da0-b107-f52d85f9746c"),
                            Stock = 20,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6029)
                        },
                        new
                        {
                            Id = new Guid("bc351238-b26c-4ea7-8b1c-3d926aa3421a"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6030),
                            IsActive = true,
                            ProductId = new Guid("530e09db-24dc-4b33-9979-b4983834a949"),
                            Stock = 30,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6031)
                        },
                        new
                        {
                            Id = new Guid("18ff1de6-aaf2-4bbb-b995-58d1d2397a8a"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6032),
                            IsActive = true,
                            ProductId = new Guid("d4f2c69e-a3ef-4c9d-9ad5-2a03db51c0d6"),
                            Stock = 50,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6032)
                        },
                        new
                        {
                            Id = new Guid("7e166e73-c995-4f4a-8058-d71b32b7df51"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6033),
                            IsActive = true,
                            ProductId = new Guid("0cb36799-db29-42f0-a0d4-a304822e07d7"),
                            Stock = 60,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6033)
                        },
                        new
                        {
                            Id = new Guid("2005d62a-4a7b-4dcd-bd84-539600f8ff80"),
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6035),
                            IsActive = true,
                            ProductId = new Guid("ce4695be-b1f3-4712-a0c6-0b866af80128"),
                            Stock = 25,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(6035)
                        });
                });

            modelBuilder.Entity("Entity.Model.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("664f59e6-f1f2-4165-a9d6-75aab245f8cf"),
                            Category = "Electronics",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5649),
                            Description = "4GB RAM 64GB ROM, 6.53-inch display",
                            IsActive = true,
                            Price = 15000.0m,
                            ProductName = "Mobile Phone",
                            Stock = 30,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5650)
                        },
                        new
                        {
                            Id = new Guid("bbadc45e-5f6d-452e-81ec-228f02c5960d"),
                            Category = "Electronics",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5657),
                            Description = "8GB RAM, 256GB SSD, 15.6-inch display",
                            IsActive = true,
                            Price = 50000.0m,
                            ProductName = "Laptop",
                            Stock = 20,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5658)
                        },
                        new
                        {
                            Id = new Guid("9207c8c3-fe61-4111-847c-60b1d739890d"),
                            Category = "Electronics",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5660),
                            Description = "43-inch 4K Ultra HD, Smart LED TV",
                            IsActive = true,
                            Price = 30000.0m,
                            ProductName = "Smart TV",
                            Stock = 15,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5660)
                        },
                        new
                        {
                            Id = new Guid("c79f9283-8aa0-4acc-b9a0-09444e38e6cd"),
                            Category = "Fashion",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5661),
                            Description = "Analog watch with leather strap",
                            IsActive = true,
                            Price = 5000.0m,
                            ProductName = "Men's Watch",
                            Stock = 50,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5661)
                        },
                        new
                        {
                            Id = new Guid("8112b552-db97-4f24-866b-58f7e2dbdc20"),
                            Category = "Fashion",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5663),
                            Description = "Stylish handbag with multiple compartments",
                            IsActive = true,
                            Price = 4000.0m,
                            ProductName = "Women's Handbag",
                            Stock = 40,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5663)
                        },
                        new
                        {
                            Id = new Guid("c68b15ac-86ee-4d93-a9cd-9c8e5886df29"),
                            Category = "Electronics",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5664),
                            Description = "Bluetooth headphones with noise cancellation",
                            IsActive = true,
                            Price = 3000.0m,
                            ProductName = "Wireless Headphones",
                            Stock = 25,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5664)
                        },
                        new
                        {
                            Id = new Guid("d2cf2963-7344-4230-a040-455ee02c6dc7"),
                            Category = "Fashion",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5665),
                            Description = "Running shoes with breathable mesh",
                            IsActive = true,
                            Price = 2500.0m,
                            ProductName = "Sports Shoes",
                            Stock = 60,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5666)
                        },
                        new
                        {
                            Id = new Guid("97ba7ea2-d733-425a-8684-115057976980"),
                            Category = "Electronics",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5667),
                            Description = "Smart band with heart rate monitor",
                            IsActive = true,
                            Price = 2000.0m,
                            ProductName = "Fitness Tracker",
                            Stock = 35,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5667)
                        },
                        new
                        {
                            Id = new Guid("a1464c2c-a4a1-4a7e-8260-3fc23c8cd3e8"),
                            Category = "Electronics",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5668),
                            Description = "10000mAh portable charger",
                            IsActive = true,
                            Price = 1500.0m,
                            ProductName = "Power Bank",
                            Stock = 45,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5668)
                        },
                        new
                        {
                            Id = new Guid("713ecd46-6bb2-401b-b4ed-f8018d9ea7ea"),
                            Category = "Home & Kitchen",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5669),
                            Description = "Non-stick cookware set with lids",
                            IsActive = true,
                            Price = 4000.0m,
                            ProductName = "Cookware Set",
                            Stock = 30,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5670)
                        },
                        new
                        {
                            Id = new Guid("3ef4fdba-4592-40b7-9ce8-f9fa927060c0"),
                            Category = "Fashion",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5671),
                            Description = "Traditional Indian saree",
                            IsActive = true,
                            Price = 3000.0m,
                            ProductName = "Saree",
                            Stock = 20,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5671)
                        },
                        new
                        {
                            Id = new Guid("43e4e9d8-3251-49c5-9221-c1f22f030ec6"),
                            Category = "Electronics",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5672),
                            Description = "Portable speaker with built-in microphone",
                            IsActive = true,
                            Price = 2500.0m,
                            ProductName = "Bluetooth Speaker",
                            Stock = 50,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5672)
                        },
                        new
                        {
                            Id = new Guid("4c84ab00-c4e0-4e3a-8ab5-ca1338acd88e"),
                            Category = "Home & Kitchen",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5673),
                            Description = "550W mixer grinder with multiple jars",
                            IsActive = true,
                            Price = 3500.0m,
                            ProductName = "Mixer Grinder",
                            Stock = 15,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5673)
                        },
                        new
                        {
                            Id = new Guid("a78d2f3b-5b7d-415e-b006-e377efbe4392"),
                            Category = "Fashion",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5674),
                            Description = "Cotton t-shirt with a cool printed design",
                            IsActive = true,
                            Price = 1000.0m,
                            ProductName = "Printed T-Shirt",
                            Stock = 70,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5675)
                        },
                        new
                        {
                            Id = new Guid("92e4d9bf-ed54-494b-8294-967ea19bc2db"),
                            Category = "Electronics",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5676),
                            Description = "1TB portable external hard drive",
                            IsActive = true,
                            Price = 5000.0m,
                            ProductName = "External Hard Drive",
                            Stock = 25,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5676)
                        },
                        new
                        {
                            Id = new Guid("2e0894c6-1ba6-4b00-bef9-d95a21e30ef0"),
                            Category = "Home & Kitchen",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5678),
                            Description = "Cotton bed sheets with pillow covers",
                            IsActive = true,
                            Price = 2000.0m,
                            ProductName = "Bed Sheets",
                            Stock = 40,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5678)
                        },
                        new
                        {
                            Id = new Guid("bef99a10-b032-4e81-9112-c91cb7971fb3"),
                            Category = "Fashion",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5679),
                            Description = "Genuine leather wallet with multiple card slots",
                            IsActive = true,
                            Price = 1500.0m,
                            ProductName = "Men's Wallet",
                            Stock = 60,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5679)
                        },
                        new
                        {
                            Id = new Guid("6424bae2-7049-45a7-9529-6c0298b394dc"),
                            Category = "Electronics",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5682),
                            Description = "HEPA filter air purifier for home",
                            IsActive = true,
                            Price = 8000.0m,
                            ProductName = "Air Purifier",
                            Stock = 10,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5683)
                        },
                        new
                        {
                            Id = new Guid("9c9c38ef-3455-4f57-9cb8-f9a33b58fe2a"),
                            Category = "Home & Kitchen",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5729),
                            Description = "Opalware dinner set with plates and bowls",
                            IsActive = true,
                            Price = 3000.0m,
                            ProductName = "Dinner Set",
                            Stock = 30,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5729)
                        },
                        new
                        {
                            Id = new Guid("652ab917-199b-4268-8b92-39bf71e859ce"),
                            Category = "Fashion",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5731),
                            Description = "Comfortable casual shoes for men",
                            IsActive = true,
                            Price = 2000.0m,
                            ProductName = "Casual Shoes",
                            Stock = 50,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5731)
                        },
                        new
                        {
                            Id = new Guid("04765c15-3ad7-4ed0-a604-8cb4078887b4"),
                            Category = "Electronics",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5732),
                            Description = "20MP DSLR camera with kit lens",
                            IsActive = true,
                            Price = 25000.0m,
                            ProductName = "Digital Camera",
                            Stock = 15,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5732)
                        },
                        new
                        {
                            Id = new Guid("6dd257e5-f534-49dd-9c67-c3ab7608de70"),
                            Category = "Fashion",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5733),
                            Description = "Stylish cotton kurti with embroidery",
                            IsActive = true,
                            Price = 1500.0m,
                            ProductName = "Women's Kurti",
                            Stock = 30,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5733)
                        },
                        new
                        {
                            Id = new Guid("535d56a0-5feb-48f6-853e-4217c5c95fa2"),
                            Category = "Electronics",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5734),
                            Description = "Latest gaming console with wireless controller",
                            IsActive = true,
                            Price = 30000.0m,
                            ProductName = "Gaming Console",
                            Stock = 10,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5735)
                        },
                        new
                        {
                            Id = new Guid("f6dc236e-7bd3-49cc-a611-c3386e7ab1b1"),
                            Category = "Home & Kitchen",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5736),
                            Description = "300W hand blender with multiple attachments",
                            IsActive = true,
                            Price = 1500.0m,
                            ProductName = "Hand Blender",
                            Stock = 25,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5736)
                        },
                        new
                        {
                            Id = new Guid("8e52187f-fd1f-4add-8f5b-a523885e4472"),
                            Category = "Fashion",
                            CreatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5737),
                            Description = "Cotton formal shirt with a slim fit",
                            IsActive = true,
                            Price = 2000.0m,
                            ProductName = "Men's Formal Shirt",
                            Stock = 40,
                            UpdatedBy = new Guid("e56fa35f-042b-4d88-a165-9b14083c2872"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5737)
                        },
                        new
                        {
                            Id = new Guid("4db5800f-fd90-47b2-bf86-0abc27020e1e"),
                            Category = "Home & Kitchen",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5739),
                            Description = "Robotic vacuum cleaner with automatic cleaning",
                            IsActive = true,
                            Price = 5000.0m,
                            ProductName = "Vacuum Cleaner",
                            Stock = 20,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5739)
                        },
                        new
                        {
                            Id = new Guid("9e9a5a67-7ffa-49f1-b015-fa6de5f5b581"),
                            Category = "Electronics",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5740),
                            Description = "Wireless earphones with charging case",
                            IsActive = true,
                            Price = 2000.0m,
                            ProductName = "Bluetooth Earphones",
                            Stock = 30,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5741)
                        },
                        new
                        {
                            Id = new Guid("2303a938-1f05-42bb-a5f0-99e7dbf77188"),
                            Category = "Home & Kitchen",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5742),
                            Description = "High-quality stainless steel knife set",
                            IsActive = true,
                            Price = 3000.0m,
                            ProductName = "Kitchen Knife Set",
                            Stock = 15,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5743)
                        },
                        new
                        {
                            Id = new Guid("9d7febe0-cb68-4d36-9a8f-4e845109e53c"),
                            Category = "Fashion",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5744),
                            Description = "Stylish sunglasses with UV protection",
                            IsActive = true,
                            Price = 1500.0m,
                            ProductName = "Women's Sunglasses",
                            Stock = 50,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5745)
                        },
                        new
                        {
                            Id = new Guid("eab5c8b2-8ae2-4bf8-827c-789ed415792c"),
                            Category = "Sports & Fitness",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5746),
                            Description = "Set of adjustable dumbbells for home workouts",
                            IsActive = true,
                            Price = 2000.0m,
                            ProductName = "Fitness Dumbbells",
                            Stock = 20,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5746)
                        },
                        new
                        {
                            Id = new Guid("28804ab1-8b21-411d-8493-cafafbd32670"),
                            Category = "Sports & Fitness",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5748),
                            Description = "Non-slip yoga mat with carrying strap",
                            IsActive = true,
                            Price = 1000.0m,
                            ProductName = "Yoga Mat",
                            Stock = 40,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5748)
                        },
                        new
                        {
                            Id = new Guid("231c7d5a-b2c9-4163-8405-147c8eec3ff6"),
                            Category = "Home & Kitchen",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5750),
                            Description = "RO water purifier with multiple purification stages",
                            IsActive = true,
                            Price = 10000.0m,
                            ProductName = "Water Purifier",
                            Stock = 10,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5750)
                        },
                        new
                        {
                            Id = new Guid("8d22a54b-4ee5-4776-9f37-6ee36b72e046"),
                            Category = "Fashion",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5751),
                            Description = "Denim jeans with a slim fit",
                            IsActive = true,
                            Price = 2500.0m,
                            ProductName = "Men's Jeans",
                            Stock = 30,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5751)
                        },
                        new
                        {
                            Id = new Guid("1c9b64eb-992f-4523-9582-935af6ffc634"),
                            Category = "Electronics",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5752),
                            Description = "Waterproof speaker with built-in microphone",
                            IsActive = true,
                            Price = 3000.0m,
                            ProductName = "Portable Bluetooth Speaker",
                            Stock = 25,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5752)
                        },
                        new
                        {
                            Id = new Guid("dbd0b3c5-6821-48f0-ac39-b56bf14cca52"),
                            Category = "Home & Kitchen",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5753),
                            Description = "Soft cotton bed sheets with floral print",
                            IsActive = true,
                            Price = 2000.0m,
                            ProductName = "Cotton Bedsheets",
                            Stock = 40,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5754)
                        },
                        new
                        {
                            Id = new Guid("8c96f86f-2e58-4d74-8ddb-d9c6539ae08a"),
                            Category = "Fashion",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5756),
                            Description = "Leather formal shoes with lace-up closure",
                            IsActive = true,
                            Price = 4000.0m,
                            ProductName = "Men's Formal Shoes",
                            Stock = 30,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5756)
                        },
                        new
                        {
                            Id = new Guid("5121ab0e-8697-4e64-aa0e-ae5f70a64699"),
                            Category = "Home & Kitchen",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5757),
                            Description = "Healthy cooking with less oil",
                            IsActive = true,
                            Price = 5000.0m,
                            ProductName = "Air Fryer",
                            Stock = 15,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5757)
                        },
                        new
                        {
                            Id = new Guid("efae2427-0391-4b22-af71-94189ea04421"),
                            Category = "Electronics",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5760),
                            Description = "Ergonomic wireless mouse with USB receiver",
                            IsActive = true,
                            Price = 1000.0m,
                            ProductName = "Wireless Mouse",
                            Stock = 50,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5760)
                        },
                        new
                        {
                            Id = new Guid("022f1827-3348-42e5-8a5a-c00fcec98e6d"),
                            Category = "Fashion",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5762),
                            Description = "Casual shorts for a comfortable summer look",
                            IsActive = true,
                            Price = 1500.0m,
                            ProductName = "Men's Shorts",
                            Stock = 60,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5762)
                        },
                        new
                        {
                            Id = new Guid("35492266-0b0b-40d2-a4bf-a1b001c9af71"),
                            Category = "Home & Kitchen",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5763),
                            Description = "Stainless steel water bottle with double insulation",
                            IsActive = true,
                            Price = 500.0m,
                            ProductName = "Water Bottle",
                            Stock = 70,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5763)
                        },
                        new
                        {
                            Id = new Guid("3ff76b36-ae8f-4fc8-916a-b5cb0cbb365b"),
                            Category = "Tools & Home Improvement",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5764),
                            Description = "Cordless power drill with multiple drill bits",
                            IsActive = true,
                            Price = 3000.0m,
                            ProductName = "Power Drill",
                            Stock = 20,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5764)
                        },
                        new
                        {
                            Id = new Guid("ec594480-1cdf-4f6a-8f59-a57252e61b46"),
                            Category = "Fashion",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5766),
                            Description = "Durable backpack with multiple compartments",
                            IsActive = true,
                            Price = 2000.0m,
                            ProductName = "School Backpack",
                            Stock = 30,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5766)
                        },
                        new
                        {
                            Id = new Guid("4a90ec34-7c7c-4b50-947f-5489894e423a"),
                            Category = "Electronics",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5767),
                            Description = "Wireless all-in-one printer for home or office",
                            IsActive = true,
                            Price = 8000.0m,
                            ProductName = "Printer",
                            Stock = 10,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5767)
                        },
                        new
                        {
                            Id = new Guid("083e888a-6a3b-485c-ba68-33e77c3e15ab"),
                            Category = "Home & Kitchen",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5768),
                            Description = "Stainless steel cooking utensils with hanging rack",
                            IsActive = true,
                            Price = 2500.0m,
                            ProductName = "Cooking Utensil Set",
                            Stock = 25,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5769)
                        },
                        new
                        {
                            Id = new Guid("de93253a-9c39-4242-b790-02c6c5a7ce7d"),
                            Category = "Fashion",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5770),
                            Description = "Comfortable sweatshirt for a casual look",
                            IsActive = true,
                            Price = 1500.0m,
                            ProductName = "Men's Sweatshirt",
                            Stock = 40,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5771)
                        },
                        new
                        {
                            Id = new Guid("10a91197-d1ac-4da0-b107-f52d85f9746c"),
                            Category = "Home & Kitchen",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5772),
                            Description = "Automatic rice cooker with multiple cooking modes",
                            IsActive = true,
                            Price = 3000.0m,
                            ProductName = "Rice Cooker",
                            Stock = 20,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5772)
                        },
                        new
                        {
                            Id = new Guid("530e09db-24dc-4b33-9979-b4983834a949"),
                            Category = "Electronics",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5773),
                            Description = "Slim wireless keyboard with ergonomic design",
                            IsActive = true,
                            Price = 2000.0m,
                            ProductName = "Wireless Keyboard",
                            Stock = 30,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5773)
                        },
                        new
                        {
                            Id = new Guid("d4f2c69e-a3ef-4c9d-9ad5-2a03db51c0d6"),
                            Category = "Home & Kitchen",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5774),
                            Description = "Modern wall clock with silent movement",
                            IsActive = true,
                            Price = 1000.0m,
                            ProductName = "Wall Clock",
                            Stock = 50,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5775)
                        },
                        new
                        {
                            Id = new Guid("0cb36799-db29-42f0-a0d4-a304822e07d7"),
                            Category = "Fashion",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5776),
                            Description = "Classic polo t-shirt with a stylish design",
                            IsActive = true,
                            Price = 1500.0m,
                            ProductName = "Men's Polo T-Shirt",
                            Stock = 60,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5776)
                        },
                        new
                        {
                            Id = new Guid("ce4695be-b1f3-4712-a0c6-0b866af80128"),
                            Category = "Electronics",
                            CreatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            CreatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5777),
                            Description = "Hands-free car kit with Bluetooth connectivity",
                            IsActive = true,
                            Price = 2000.0m,
                            ProductName = "Bluetooth Car Kit",
                            Stock = 25,
                            UpdatedBy = new Guid("e71f575c-1c70-4f83-b8b0-8021a853b1ef"),
                            UpdatedOn = new DateTime(2023, 7, 12, 11, 54, 33, 160, DateTimeKind.Utc).AddTicks(5778)
                        });
                });

            modelBuilder.Entity("Entity.Model.Inventory", b =>
                {
                    b.HasOne("Entity.Model.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entity.Model.Product", b =>
                {
                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
